VDS-2369
VirtoCommerce/vc-demo-xapi-app pull request #37
Opened 2021-08-16 09:56 UTC by asvishnyakov

Description: 

--

QA-test: 

Demo-test: 

Download artifact URL:

2021-08-16 12:43 UTC, ilyawzrd approved these changes

2021-08-16 15:52 UTC, trueboroda requested changes

2021-08-16 15:52 UTC, trueboroda commented on src/app/modules/companies/store/companies.reducer.ts
> +        .find(x => x?.name === 'Short text | Usual')?.value as string | null,
Move dyn props names to constants.

2021-08-17 07:27 UTC, asvishnyakov commented on src/app/modules/companies/store/companies.reducer.ts
> +        .find(x => x?.name === 'Short text | Usual')?.value as string | null,
Fixed

2021-08-17 07:40 UTC, trueboroda approved these changes

2021-08-18 09:16 UTC, merged